### ISSUE TITLE
Great improvement!

### ISSUE THREAD

**Issue by MakerMeik** [gadjet/Window_Door-Sensor#1]
Hi Gadjet,

unfortunately, Youtube occasionally eats comments, but I found the reference to your completed project in the email notification and am thrilled. I've pinned a corresponding link in the comments of my video.

Thanks for sharing your ideas and additions. I do my videos for people like you: Knowledge doubles when you share it. :-)

**Comment by gadjet** [comment]
Thanks, I have another design using a step-up booster so it can use a 1.5V battery and it's a lot smaller.
