### ISSUE TITLE
Device not reseting when when door is closing

### ISSUE THREAD

**Issue by sheminasalam** [gadjet/Window_Door-Sensor#3]
Hi there, we have talked before of this same issue and you gave me pointers to sort it then but now it has again happened. Hope you can help me now also. 

This is my pcb. The circuit is the same but I coverted it to hole through components as i am not expert with smd.

![image](https://user-images.githubusercontent.com/45196177/205426667-1d88fc2a-f0a8-4d6d-9a2d-86827c441ddd.png)

I am using HT7333 LDO now with 1000uf capacitor for ESP(in PCB its shown as 100nf) and 100nf between ground and SN74HC86N. 
Battery is 18560 

The issue that the device doesnot update when door is closed. I tried to debug it with the limited tools I have found it was not a software thing as the led on the esp8266 board doesn't even light up when closing. On further investigation I found that when closing the GPIO 13 pin pulled high also but the Enable pin of esp is not grounded.

what is the purpose of the 2nd 100nf capacitor? should I try a more powerful capacitor instead of 100nf.

Can you give some pointers?

**Comment by gadjet** [comment]
Hi,
Do you have the circuit diagram? the PCB is quite difficult to follow.

**Comment by gadjet** [comment]
Are the values shown on the PCB components correct, the 100nF above the battery connector should be 1uF not 100nF.

**Comment by sheminasalam** [comment]
I was using 100nf, will change to 1uf and see if anything changes. 

I build my pcb using your pcb file and there it was 100nf. Maybe You have updated to 1uf and I might have failed to update.
![image](https://user-images.githubusercontent.com/45196177/205439909-62820bbc-2180-4b52-b3e8-d55970e423d2.png)


I don't have the circuit diagram as I assembled looking from your pcb and circuit. I will upload pcb screenshot without grids. Hope this helps.

![image](https://user-images.githubusercontent.com/45196177/205439728-e289a645-549a-452a-bff0-ab743d6a0c13.png)

**Comment by sheminasalam** [comment]
I dont have 1uf in stock. Will it be ok if I use 10uf?

Also just a question. Can we replace the 1M ohm resistor connecting the reed switch with vcc with 10k resistor? I am currently using 1M only but wanted to know if there is any issue with 10k is used instead.

**Comment by gadjet** [comment]
That capacitor determines the pulse 10uf should be OK but I can't be sure, you could try an online simulation to see the difference.
The 1M Resistor pull up can be swapped for a 10k but it will increase the quiescent current.
One suggestion is the PCB should really have thicker supply tracks to the ESP, ideally GND and VCC power planes should be used.

**Comment by gadjet** [comment]
When you look at the enable pin it only gets toggled very quickly to wake up the ESP each time the switch is opened or closed, you would need an oscilloscope to monitor it.

**Comment by sheminasalam** [comment]
I will try with simulation.

To thicken the supply track, in this case I will use a 1mm single core wire to connect the vcc and gnd directly to esp12f. Hope that woud give an additional route for power. I will certainly keep the use of gnd and vcc planes in my next designing.

Thanks. Appreciate the timely response. Will update with the results...
