### ISSUE TITLE
Esp8266 battery operated smoke alarm

### ISSUE THREAD

**Issue by sheminasalam** [gadjet/Window_Door-Sensor#4]
First, please accept my appologies for opening an issue but i didn't have any other discusions open in your threads. I want to know if it would be possible to design a battery(18650) operated smoke sensor(MQ2 sensor module) with esp8266. The thing is that there are many tutorials which work on DC supply. There is one which hacks a [traditional smoke detector ](https://www.youtube.com/watch?v=7ZcnPoZn_O0) but not MQ2 sensor module. How would the circuit look like for max battery savings.

**Comment by gadjet** [comment]
Hi, try this page?
https://circuitdigest.com/microcontroller-projects/interfacing-mq2-gas-sensor-with-arduino
If the MOS gives a positive thrigger when there is smoke it could be used to trigger the Version 5 module, also on my github, although the MOS will need to be permenantly powered up.

**Comment by gadjet** [comment]
The sensor will consume around 160mA so not a good candidate for battery power unless you have a very big battery
